version: "3"
services:
  redis:
    image: redis
    restart: always

  db:
    image: postgres:9.4
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

  vote:
    image: voting-app
    ports:
      - "5000:80"
    depends_on:
      - redis
      - db

  worker:
    image: worker-app
    depends_on:
      - redis
      - db

  result:
    image: result-app
    ports:
      - "5001:80"
    depends_on:
      - db
